// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHx9PEyFzS7GMHYBNp8CvKTvlk70K9bfE',
    appId: '1:16303075013:web:57465f7b7f6360a765caac',
    messagingSenderId: '16303075013',
    projectId: 'flutter--maps-36cb3',
    authDomain: 'flutter--maps-36cb3.firebaseapp.com',
    storageBucket: 'flutter--maps-36cb3.appspot.com',
    measurementId: 'G-MQTE21VM6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcdXtDkbAvoS43gjvrAnzzR7BW_8IN0Gk',
    appId: '1:16303075013:android:c28df1e4c999326665caac',
    messagingSenderId: '16303075013',
    projectId: 'flutter--maps-36cb3',
    storageBucket: 'flutter--maps-36cb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk31DsN0XovSn4r8CjZkfUEtblwh94y_4',
    appId: '1:16303075013:ios:8761717dafc2653265caac',
    messagingSenderId: '16303075013',
    projectId: 'flutter--maps-36cb3',
    storageBucket: 'flutter--maps-36cb3.appspot.com',
    iosBundleId: 'com.example.flutterGoogleMaps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk31DsN0XovSn4r8CjZkfUEtblwh94y_4',
    appId: '1:16303075013:ios:8761717dafc2653265caac',
    messagingSenderId: '16303075013',
    projectId: 'flutter--maps-36cb3',
    storageBucket: 'flutter--maps-36cb3.appspot.com',
    iosBundleId: 'com.example.flutterGoogleMaps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHx9PEyFzS7GMHYBNp8CvKTvlk70K9bfE',
    appId: '1:16303075013:web:761517d5605220ed65caac',
    messagingSenderId: '16303075013',
    projectId: 'flutter--maps-36cb3',
    authDomain: 'flutter--maps-36cb3.firebaseapp.com',
    storageBucket: 'flutter--maps-36cb3.appspot.com',
    measurementId: 'G-LXH8BEBH3Y',
  );
}
